
// Objective-C API for talking to the following Go packages
//
//	github.com/Jigsaw-Code/outline-apps/client/go/outline/platerrors
//	github.com/Jigsaw-Code/outline-apps/client/go/outline/tun2socks
//	github.com/Jigsaw-Code/outline-apps/client/go/outline
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tun2socks_FRAMEWORK_H__
#define __Tun2socks_FRAMEWORK_H__

#include "Platerrors.objc.h"
#include "Tun2socks.objc.h"
#include "Outline.objc.h"
#include "Universe.objc.h"

#endif
